title: TalkBook blog
description: Company updates and technology and public speaking articles

baseurl: ""
url: "http://blog.talkbook.co" # the base hostname & protocol for your site

email: info@talkbook.co
github_username:
twitter_username:
linkedin_username:

# Build settings
markdown: kramdown

exclude:
  - vendor
  - README.md
